name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean test #-Dtestng.dtd.http=true

    - name: Cucumber HTML reports
      uses: actions/upload-artifact@v2
      with:
        name: cucumber-reports
        path: ./test-output/Execution reports/ExtentHtml.html # Specify the directory where your HTML reports are generated 
        
    - name: Copy Reports to Deployment Directory
      run: |
        mkdir -p deployment/reports  # Create a directory to hold reports in deployment
        cp -r ./test-output/Execution reports/ExtentHtml.html deployment/reports/

    - name: Commit and Push to GitHub Pages
      run: |
        cd deployment
        git init
        git add .
        git commit -m "Deploy reports to GitHub Pages"
        git push --force "https://${{ secrets.GITHUB_TOKEN }}@github.com/shubhamdhiman2022/GithubActionDemo1.git" HEAD:gh-pages     

#    - name: Deploy report page to GitHub Page
#      uses: peaceiris/actions-gh-pages@v3
#      with: 
#        github_token: ${{ secrets.GITHUB_TOKEN }}
#        publish_dir: /test-output/Execution reports/ExtentSpark.html
